[project]
name = "cookareq"
version = "0.1.0"
authors = [{ name = "Maksim Lashkevich & Codex" }]
license = { file = "LICENSE" }
dependencies = [
    "wxPython",
    "jsonschema",
    "fastapi",
    "uvicorn",
    "mcp",
    "openai",
]

[project.optional-dependencies]
dev = ["pytest", "polib", "pydocstyle"]

[tool.pydocstyle]
select = ["D100", "D101", "D102", "D103"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
