[project]
name = "cookareq"
version = "0.1.0"
authors = [{ name = "Maksim Lashkevich & Codex" }]
license = { file = "LICENSE" }
dependencies = [
    "wxPython",
    "jsonschema",
    "fastapi",
    "uvicorn",
    "mcp",
    "openai",
]

[project.optional-dependencies]
dev = ["pytest", "polib", "pydocstyle", "ruff"]

[tool.pydocstyle]
select = ["D100", "D101", "D102", "D103", "D104", "D107"]

[tool.ruff]
exclude = [
    "build",
    "dist",
    ".venv",
    "**/migrations/*",
]

[tool.ruff.lint]
select = [
    "E9",
    "E741",
    "F63",
    "F7",
    "F82",
    "F401",
    "F841",
    "B",
    "UP",
    "I",
    "W",
    "C4",
    "COM",
    "A",
    "ARG",
    "SIM",
    "RUF",
    "PTH",
    "RET",
    "T20",
    "N",
    "DTZ",
    "PERF",
    "Q",
    "SLF",
    "TRY",
]

ignore = ["RUF001", "RUF003", "TRY003"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["ARG001", "ARG002", "ARG003", "ARG004", "ARG005", "N802", "SLF001"]
"app/ui/helpers.py" = ["N802", "N803"]
"app/ui/list_panel.py" = ["N802"]
"app/ui/labels_dialog.py" = ["N802"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
