"""Document store public API."""

from __future__ import annotations

from .types import (
    Document,
    DocumentLabels,
    DocumentNotFoundError,
    LabelDef,
    RequirementError,
    RequirementIDCollisionError,
    RequirementNotFoundError,
    RequirementPage,
    ValidationError,
)
from .documents import (
    collect_label_defs,
    collect_labels,
    is_ancestor,
    label_color,
    load_document,
    load_documents,
    save_document,
    stable_color,
    validate_labels,
)
from .items import (
    create_requirement,
    delete_requirement,
    get_requirement,
    item_path,
    list_item_ids,
    list_requirements,
    load_item,
    load_requirements,
    move_requirement,
    next_item_id,
    parse_rid,
    rid_for,
    save_item,
    search_requirements,
    set_requirement_attachments,
    set_requirement_labels,
    set_requirement_links,
    update_requirement_field,
)
from .links import (
    delete_document,
    delete_item,
    iter_links,
    link_requirements,
    plan_delete_document,
    plan_delete_item,
)

__all__ = [
    "ValidationError",
    "RequirementError",
    "DocumentNotFoundError",
    "RequirementNotFoundError",
    "RequirementIDCollisionError",
    "LabelDef",
    "DocumentLabels",
    "Document",
    "RequirementPage",
    "collect_label_defs",
    "collect_labels",
    "is_ancestor",
    "label_color",
    "load_document",
    "load_documents",
    "save_document",
    "stable_color",
    "validate_labels",
    "create_requirement",
    "delete_requirement",
    "get_requirement",
    "load_requirements",
    "item_path",
    "list_item_ids",
    "list_requirements",
    "load_item",
    "move_requirement",
    "next_item_id",
    "parse_rid",
    "rid_for",
    "save_item",
    "search_requirements",
    "set_requirement_attachments",
    "set_requirement_labels",
    "set_requirement_links",
    "update_requirement_field",
    "delete_document",
    "delete_item",
    "iter_links",
    "link_requirements",
    "plan_delete_document",
    "plan_delete_item",
]
